In [6]:
import pandas as pd

df = pd.read_csv('data/iris.csv')
print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [7]:
print(df.head)

<bound method NDFrame.head of      sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]>


In [8]:
print(df.shape)

(150, 5)


In [9]:
print(df.index)

RangeIndex(start=0, stop=150, step=1)


In [10]:
print(df.iloc[1])

sepal_length       4.9
sepal_width        3.0
petal_length       1.4
petal_width        0.2
species         setosa
Name: 1, dtype: object


In [11]:
print(df.iloc[1,1])

3.0


In [12]:
print(df.columns)

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')


In [15]:
X = df[["sepal_length","sepal_width","petal_length","petal_width"]].to_numpy()
y = df[["species"]]
print(type(X))
print(type(y))
print(X.shape)
print(y.shape)

<class 'numpy.ndarray'>
<class 'pandas.core.frame.DataFrame'>
(150, 4)
(150, 1)


In [1]:
from sklearn.metrics import confusion_matrix
actual = [0, 1, 0, 1]
predicted = [1, 1, 1, 0]
cm = confusion_matrix(actual, predicted)
print(type(cm))
print(" ", "0 ", "1 ", "P ")
print(0, "TN", "FP")
print(1, "FN", "TP")
print("A")
print()
print("confusion matrix")
print(cm)

<class 'numpy.ndarray'>
  0  1  P 
0 TN FP
1 FN TP
A

confusion matrix
[[0 2]
 [1 1]]


In [8]:
from sklearn.metrics import confusion_matrix
actual = ['B', 'M', 'B', 'M']
predicted = ['M', 'M', 'M', 'B']
cm = confusion_matrix(actual, predicted)
print("confusion matrix")
print(cm)


confusion matrix
[[0 2]
 [1 1]]


In [9]:
# ravel - returns a flattened array in row major style
r = cm.ravel()
print(type(r))
tn, fp, fn, tp = cm.ravel()
print("TN", tn, "FP", fp, "FN", fn, "TP", tp)


<class 'numpy.ndarray'>
TN 0 FP 2 FN 1 TP 1


In [10]:
from sklearn.metrics import confusion_matrix
actual= ["cat", "ant", "cat", "cat", "ant", "bird"]
predicted = ["ant", "ant", "cat", "cat", "ant", "cat"]
cm = confusion_matrix(actual, predicted)
print("confusion matrix")
print(cm)

confusion matrix
[[2 0 0]
 [0 0 1]
 [1 0 2]]


In [11]:
#to change the order and put cat as second
from sklearn.metrics import confusion_matrix
actual= ["cat", "ant", "cat", "cat", "ant", "bird"]
predicted = ["ant", "ant", "cat", "cat", "ant", "cat"]
cm = confusion_matrix(actual, predicted, labels=["ant", "cat", "bird"])
print(cm)

[[2 0 0]
 [1 2 0]
 [0 1 0]]


In [14]:
from sklearn.datasets import load_iris
import numpy as np
iris = load_iris()
print(type(iris))
print(iris.feature_names)
print(iris.target_names)

X = iris.data
print("X.shape", X.shape)
y = iris.target
print("y.shape", y.shape)
print(y)
print(iris.DESCR)

<class 'sklearn.utils.Bunch'>
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']
X.shape (150, 4)
y.shape (150,)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary 